// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpPaJGvtPL3N7pJM0Zq-eVe2NMxfrA5Ts',
    appId: '1:919524899349:web:894f15e5ae88257d1bec1c',
    messagingSenderId: '919524899349',
    projectId: 'home-less-hore',
    authDomain: 'home-less-hore.firebaseapp.com',
    storageBucket: 'home-less-hore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0SCwUX1PK5QersalmcjSDWT0LmFch6JM',
    appId: '1:919524899349:android:947b3739ef28113a1bec1c',
    messagingSenderId: '919524899349',
    projectId: 'home-less-hore',
    storageBucket: 'home-less-hore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsnauyvl4CjcYUoQJb21hkLABczE1wwYM',
    appId: '1:919524899349:ios:8b73792cae76653d1bec1c',
    messagingSenderId: '919524899349',
    projectId: 'home-less-hore',
    storageBucket: 'home-less-hore.appspot.com',
    iosBundleId: 'com.example.homely',
  );
}
